version: "3"
services:
  nginx:
    ports:
      - "80:80"
  node-app-image:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production   
    command: node index.js   